import js from './js.png';

// n초 뒤에 실행 되게하는 promise
// const sleep = n => new Promise(resolve => setTimeout(resolve, n));

// 'wrwrwerwerwerwerewrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrrertyyyyyyyyttttttttttwerwerwerwerwerwerwerwerwerwerwerwer'
const posts = [
  {
    id: 1,
    img: js,
    title: '포스트1',
    desc: '포스트1 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2,
    img: js,
    title: '포스트2',
    desc: '포스트2 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 3,
    img: js,
    title: '포스트3',
    desc: '포스트3 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 4,
    img: js,
    title: '포스트4',
    desc: '포스트4 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 5,
    img: js,
    title: '포스트5',
    desc: '포스트5 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 6,
    img: js,
    title: '포스트6',
    desc: '포스트6 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 7,
    img: js,
    title: '포스트7',
    desc: '포스트7 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 8,
    img: js,
    title: '포스트8',
    desc: '포스트8 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 9,
    img: js,
    title: '포스트9',
    desc: '포스트9 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 10,
    img: js,
    title: '포스트10',
    desc: '포스트10 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 11,
    img: js,
    title: '포스트11',
    desc: '포스트11 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 12,
    img: js,
    title: '포스트12',
    desc: '포스트12 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 13,
    img: js,
    title: '포스트13',
    desc: '포스트13 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 14,
    img: js,
    title: '포스트14',
    desc: '포스트14 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 15,
    img: js,
    title: '포스트15',
    desc: '포스트15 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 16,
    img: js,
    title: '포스트16',
    desc: '포스트16 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 17,
    img: js,
    title: '포스트17',
    desc: '포스트17 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 18,
    img: js,
    title: '포스트18',
    desc: '포스트18 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 19,
    img: js,
    title: '포스트19',
    desc: '포스트19 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 20,
    img: js,
    title: '포스트20',
    desc: '포스트20 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 21,
    img: js,
    title: '포스트21',
    desc: '포스트21 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 22,
    img: js,
    title: '포스트22',
    desc: '포스트22 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 23,
    img: js,
    title: '포스트23',
    desc: '포스트23 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 24,
    img: js,
    title: '포스트24',
    desc: '포스트24 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 25,
    img: js,
    title: '포스트25',
    desc: '포스트25 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 147800,
    img: js,
    title: '포스트14',
    desc: '포스트14 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 1532,
    img: js,
    title: '포스트15',
    desc: '포스트15 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 1612,
    img: js,
    title: '포스트16',
    desc: '포스트16 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 178,
    img: js,
    title: '포스트17',
    desc: '포스트17 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 181,
    img: js,
    title: '포스트18',
    desc: '포스트18 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 19098,
    img: js,
    title: '포스트19',
    desc: '포스트19 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2065,
    img: js,
    title: '포스트20',
    desc: '포스트20 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 217,
    img: js,
    title: '포스트21',
    desc: '포스트21 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 202,
    img: js,
    title: '포스트22',
    desc: '포스트22 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 23098,
    img: js,
    title: '포스트23',
    desc: '포스트23 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 24532,
    img: js,
    title: '포스트36',
    desc: '포스트24 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 3721,
    img: js,
    title: '포스트37',
    desc: '포스트37 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 142,
    img: js,
    title: '포스트14',
    desc: '포스트14 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 153,
    img: js,
    title: '포스트15',
    desc: '포스트15 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 162,
    img: js,
    title: '포스트16',
    desc: '포스트16 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 1714,
    img: js,
    title: '포스트17',
    desc: '포스트17 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 18123,
    img: js,
    title: '포스트18',
    desc: '포스트18 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 191,
    img: js,
    title: '포스트19',
    desc: '포스트19 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2032,
    img: js,
    title: '포스트20',
    desc: '포스트20 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2189,
    img: js,
    title: '포스트21',
    desc: '포스트21 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2267,
    img: js,
    title: '포스트22',
    desc: '포스트22 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2345,
    img: js,
    title: '포스트23',
    desc: '포스트23 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 371,
    img: js,
    title: '포스트48',
    desc: '포스트48 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 3721,
    img: js,
    title: '포스트49',
    desc: '포스트37 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 142,
    img: js,
    title: '포스트14',
    desc: '포스트14 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 153,
    img: js,
    title: '포스트15',
    desc: '포스트15 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 162,
    img: js,
    title: '포스트16',
    desc: '포스트16 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 1714,
    img: js,
    title: '포스트17',
    desc: '포스트17 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 18123,
    img: js,
    title: '포스트18',
    desc: '포스트18 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 191,
    img: js,
    title: '포스트19',
    desc: '포스트19 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2032,
    img: js,
    title: '포스트20',
    desc: '포스트20 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2189,
    img: js,
    title: '포스트21',
    desc: '포스트21 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2267,
    img: js,
    title: '포스트22',
    desc: '포스트22 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2345,
    img: js,
    title: '포스트23',
    desc: '포스트23 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 371,
    img: js,
    title: '포스트60',
    desc: '포스트48 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 3721,
    img: js,
    title: '포스트61',
    desc: '포스트49 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 142123456,
    img: js,
    title: '포스트62',
    desc: '포스트14 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 15334467,
    img: js,
    title: '포스트15',
    desc: '포스트15 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 1628907,
    img: js,
    title: '포스트16',
    desc: '포스트16 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 171432156,
    img: js,
    title: '포스트17',
    desc: '포스트17 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 18123789655,
    img: js,
    title: '포스트18',
    desc: '포스트18 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 19156789,
    img: js,
    title: '포스트19',
    desc: '포스트19 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 20329087653,
    img: js,
    title: '포스트20',
    desc: '포스트20 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2189321678,
    img: js,
    title: '포스트21',
    desc: '포스트21 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2267987650,
    img: js,
    title: '포스트22',
    desc: '포스트22 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 2345098765,
    img: js,
    title: '포스트23',
    desc: '포스트23 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
  {
    id: 37123167890,
    img: js,
    title: '포스트72',
    desc: '포스트48 입니다.',
    date: '최근',
    user: 'administrator',
    comments: 7,
    views: 100,
  },
]

export const PostsAPI = () => {
  // await sleep(1000);
  return posts;
}